### ISSUE TITLE
Write arm trajectory optimization test

### ISSUE THREAD

**Issue by thomas-moulard** [roboptim/roboptim-retargeting#3]
Currently implemented in tests/minimum-jerk-problem.cc (a better name should be found).
- [x] minimum jerk trajectory generation
- [x] implement cost function (acceleration), 75% ok
- [x] problem definition
- [x] add ZMP constraint, see #2 
- [x] add foot position constraint
- [x] add full log with curves of the whole optimization process with intermediary values. This requires some modifications in roboptim-core. See the following tickets:
  - [x] roboptim/roboptim-core#22
  - [x] roboptim/roboptim-core#28
- [x] limit joints positions and velocities ( #21 , #22 )
